EMOJIS = {
    "smile": "😄",
    "happy": "😃",
    "laugh": "😂",
    "sad": "😢",
    "cry": "😭",
    "angry": "😠",
    "cool": "😎",
    "thinking": "🤔",
    "thumb_up": "👍",
    "thumb_down": "👎",
    "check": "✅",
    "cross": "❌",
    "heart": "❤️",
    "fire": "🔥",
    "star": "⭐",
    "poop": "💩",
    "rocket": "🚀",
    "party": "🎉",
    "gift": "🎁",
    "clap": "👏",
    "pray": "🙏",
    "ok": "👌",
    "peace": "✌️",
    "love": "🥰",
    "wink": "😉",
    "shrug": "🤷",
    "facepalm": "🤦",
    "robot": "🤖",
    "alien": "👽",
    "ghost": "👻",
    "skull": "💀",
    "cat": "🐱",
    "dog": "🐶",
    "monkey": "🐵",
    "fox": "🦊",
    "pizza": "🍕",
    "burger": "🍔",
    "beer": "🍺",
    "coffee": "☕",
    "computer": "💻",
    "phone": "📱",
    "watch": "⌚",
    "camera": "📷",
    "video": "📹",
    "music": "🎵",
    "game": "🎮",
    "book": "📖",
    "pen": "🖊️",
    "pencil": "✏️",
    "sun": "☀️",
    "moon": "🌙",
    "rain": "🌧️",
    "cloud": "☁️",
    "snow": "❄️",
    "lightning": "⚡",
    "tree": "🌳",
    "flower": "🌸",
    "car": "🚗",
    "bus": "🚌",
    "train": "🚆",
    "plane": "✈️",
    "ship": "🚢",
    "bike": "🚲",
    "house": "🏠",
    "office": "🏢",
    "hospital": "🏥",
    "bank": "🏦",
    "school": "🏫",
    "money": "💰",
    "card": "💳",
    "chart": "📈",
    "lock": "🔒",
    "unlock": "🔓",
    "key": "🔑",
    "tool": "🛠️",
    "search": "🔍",
    "link": "🔗",
    "mail": "📧",
    "warning": "⚠️",
    "info": "ℹ️",
    "question": "❓",
    "exclamation": "❗",
    "plus": "➕",
    "minus": "➖",
    "divide": "➗",
    "multiply": "✖️",
    "equal": "🟰",
    "hash": "#️⃣",
    "at": "@",
    "copyright": "©️",
    "trademark": "™️",
    "registered": "®️",
    "flag_us": "🇺🇸",
    "flag_uk": "🇬🇧",
    "flag_eu": "🇪🇺",
    "flag_in": "🇮🇳",
    "flag_jp": "🇯🇵",
    "flag_cn": "🇨🇳",
    "flag_de": "🇩🇪",
    "flag_fr": "🇫🇷",
    "flag_it": "🇮🇹",
    "flag_es": "🇪🇸",
    "flag_ru": "🇷🇺",
    "flag_br": "🇧🇷",
    "flag_ca": "🇨🇦",
    "flag_au": "🇦🇺",
    "earth": "🌍",
    "globe": "🌐"
}

def search_emojis(query):
    query = query.lower()
    return [
        {
            "name": name,
            "char": char,
            "description": f"Copy {char}"
        }
        for name, char in EMOJIS.items()
        if query in name
    ]
